menu:
  about: /about
favicon:
  enable: true
  icon: /image/icon/vista_messenger.jpg
profile:
  enable: true
  author: '梦不见电子羊'
  avatar: '/image/icon/avatar.jpg'  # Your avatar image, for example, https://avatars.githubusercontent.com/username
  avatar_link: '' # The link you click on the avatar and jump to, for example, https://github.com/username
  social: # you can customize which and how many social links to show
    - name: Github
      link: 'https://github.com/Cantdreamofelectronicsheep' # https://github.com/username
      icon: /image/icon/github.png
    - name: Bilibili
      link: 'https://space.bilibili.com/399759033' 
      icon: /image/icon/bilibili.png
    - name: douyin
      link: 'https://v.douyin.com/hk2UzeSGL6k/' 
      icon: /image/icon/tiktok.png
music:
  enable: true
  autoplay: false
  songs:
    - title: 'ミスティック ブルース'
      artist: '具島直子'
      cover: '/image/icon/ミスティック ブルース.jpg'
      url: 'https://java-ai-yds.oss-cn-beijing.aliyuncs.com/music/%E5%85%B7%E5%B3%B6%E7%9B%B4%E5%AD%90%20-%20%E3%83%9F%E3%82%B9%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%20%E3%83%96%E3%83%AB%E3%83%BC%E3%82%B9_min.mp3'
math:
  enable: true
  engine: mathjax

waline:
  enable: true
  serverURL: 'https://blog-waline-kappa-roan.vercel.app'
